name: PHP Composer

on:
  
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Update ReadMe
      run: php index.php
    
    - name: Commit ReadMe
      run: |
        git config --global user.email "daipham31@outlook.com"
        git config --global user.name "daipham31"
        git add .
        git commit -m "Updated README.md" || echo "No changes to commit"
        git push

